### ISSUE TITLE
FYI: url-http-end-of-headers

### ISSUE THREAD

**Issue by alphapapa** [davep/quiz.el#1]
Hi,

FYI, you can use the variable `url-http-end-of-headers` instead of doing a regexp search yourself.  I only found out about this recently myself, from looking at someone else's package.  :)

**Comment by davep** [comment]
Do you happen to know if it's reliable now? I seem to recall trying it some time ago (in a different package) and having issues, and I've seen others mention that it's unreliable. 

(it's also concerning that it actually isn't documented; not in the source and, as far as I can see, in the manual)

**Comment by alphapapa** [comment]
Oh, I see.  Well, I guess I can't speak to its reliability much.  I saw someone using it in a package of theirs, and then I started using it in `org-web-tools`, and so far it's been working fine.  Maybe you're smart to not depend on it yet.

**Comment by davep** [comment]
Okay, good to know it is reliable and being used. I'll look at trying it it out. 

Thanks.
